* CLIP 1.4 (Common Lisp Interface Package)

This is a copy of CLIP 1.4 from January 1994, slightly modified to work with
modern systems:
- Added README and .ps converted to .pdf
- CLTL2 is not bleeding edge any more, actually, there is a new standard there
- Use closer-mop for access to MOP
- I am sure that bundled portable-defsystem was nice, but asdf is standard now
- Apparently, it used to be possible to declare named VALUES

Not to be confused with Clips, Clisp.

Originally designed to be used with Clasp (statistics package, not the new CL
implementation), but output files work with any modern systems (e.g., R) as well.

** What does it do
See [[file:doc/manual.pdf][manual]]. Basically, define separately
- a system that needs to be observed/measured, aka simulation
- collection of measurements that can be done, aka clips, as in alligator clips (e.g., values of variables). These can be run once per trial, on a trigger, or on a schedule
- a set of experiments on the simulation that use clips to do measurements of individual trials under varying conditions
and then run the experiments and report results to the file

** Known bugs
See [[file:doc/clip-1.4/release-notes.text][release notes]], plus:
- newer CL implementations (such as sbcl) need to be told how to advice functions if you want to use trigger based clips. It might be more portable to use [[file:after-2020/notes.org][callbacks in a variable]], though.

** Motivation
I recalled the package when I had an aligned need (separate experiment
definition from main code), and I am not aware of modern alternative.

Also, the software is no longer available on the original location - actually, the hardest part was to find the original source.

** Added to the original
- asdf system definition (clip-1994)
- there is a reader of CLASP format now in [[./new-code/frame-loader.lisp]] (asdf system clip-1992/loader)

** Copyright
This is the original copyright. Based on that, I assume that publishing this is OK. My new code, if any relevant, is under the MIT license.
#+begin_quote
Copyright (c) 1994 University of Massachusetts
Department of Computer Science
Experimental Knowledge Systems Laboratory
Professor Paul Cohen, Director.
All rights reserved.

Permission to use, copy, modify and distribute this software and its
documentation is hereby granted without fee for non-commercial uses
only (not for resale), provided that the above copyright notice of EKSL,
this paragraph and the one following appear in all copies and in
supporting documentation.

EKSL makes no representation about the suitability of this software for any
purposes.  It is provided "AS IS", without express or implied warranties
including (but not limited to) all implied warranties of merchantability
and fitness for a particular purpose, and notwithstanding any other
provision contained herein.  In no event shall EKSL be liable for any
special, indirect or consequential damages whatsoever resulting from loss
of use, data or profits, whether in an action of contract, negligence or
other tortuous action, arising out of or in connection with the use or
performance of this software, even if EKSL is advised of the possiblity
of such damages.
#+end_quote
